### ISSUE TITLE
CLI: pac package show & pac package deploy fails when pac auth not initialised

### ISSUE THREAD

**Issue by TDX-RB** [MicrosoftDocs/power-platform#2083]
Hi,

I received the following error when running **pac package show -p package.dll**
```
PS C:\pac\> pac package show -p package.dll
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 2e55cfa8-59a0-487d-9af5-46cd6b425add, Exception Type: System.NullReferenceException
The diagnostic logs can be found at: C:\Users\<name>\AppData\Local\Microsoft\PowerAppsCLI\Microsoft.PowerApps.CLI.1.25.5\tools\logs\pac-log.txt
```
An error also occurs when using **pac package deploy -p package.dll**
```
PS C:\pac\> pac package deploy --package package.dll
Microsoft PowerPlatform CLI
Version: 1.25.5+g24fc1f8
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Object reference not set to an instance of an object.

Usage: pac package deploy [--logFile] [--logConsole] --package [--settings] [--verbose]

  --logFile                   Log file path (alias: -lf)
  --logConsole                Output log to console (alias: -c)
  --package                   Path to a package dll or zip file with a package. (alias: -p)
  --settings                  Runtime Package Settings that are passed to the package that is being deployed. The format of the string must be `key=value|key=value`. (alias: -s)
  --verbose                   Emit verbose logs to the log outputs. (alias: -vdbg)
```

This error is present on version 1.23.3 onwards, is not present on 1.22.4

It also looks like that when **pac auth create --url \<environment>** is used prior, the error does not appear and the functionality works as expected, however, in versions 1.22.4 and prior, this correctly alerted the user to connect to an environment:
```
PS C:\pac> pac package show -p package.dll
Microsoft PowerPlatform CLI
Version: 1.22.4+gfad5a46

Error: No profiles were found of kind DATAVERSE, UNIVERSAL on this computer. Please run 'pac auth create --kind DATAVERSE' to create one.

Usage: pac package show --package [--logFile] [--verbose]

  --package                   path to a package dll or zip file with a package (alias: -p)
  --logFile                   Log file path (alias: -lf)
  --verbose                   Emit Verbose logs to the log outputs (alias: -vdbg)
```

Stacktrace from pac-log.txt
```
2023-08-03 09:19:36.8268 | INF | bolt.Session :: Product Version: 1.25.5+g24fc1f8; File Version: 1.25.5
2023-08-03 09:19:36.8693 | INF | bolt.Session :: Start new session. (sessionId: d7d38e48-a62d-4618-b227-45158c095dfe; operationId: 026abff42b4401130c71f643150de9a9; userId: c1bc9c34-fb8b-4989-88d6-06cff08819a5)
2023-08-03 09:19:37.2661 | INF | bolt.cli.CommandProcessor :: StartExecutingVerb (Verbs: ["package","show"])
2023-08-03 09:19:37.2841 | INF | bolt.cli.Verb :: Executing 'show' verb
2023-08-03 09:19:37.3495 | INF | bolt.module.package.PackageDeployment :: Initializing package deployment
2023-08-03 09:19:37.3554 | INF | bolt.module.package.PackageDeployment :: Initializing logging
2023-08-03 09:19:37.3883 | INF | bolt.module.package.PackageDeployment :: Setup authentication
2023-08-03 09:19:37.3883 | INF | bolt.authentication.profiles.FileBasedAuthProfilesManager :: ReadSettings(): No settings file found, creating a default one
2023-08-03 09:19:37.3883 | INF | bolt.authentication.profiles.FileBasedAuthProfilesManager :: GetCurrent(): For Kind 'DATAVERSE'.
2023-08-03 09:19:37.3883 | INF | bolt.authentication.profiles.FileBasedAuthProfilesManager :: GetCurrent(): For Kind 'UNIVERSAL'.
2023-08-03 09:19:37.4153 | INF | bolt.cli.CommandProcessor :: EndExecutingVerb (Success: False, Execution Time(ms): 139)
2023-08-03 09:19:37.4512 | FTL | bolt.Session :: Object reference not set to an instance of an object.|EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
   at bolt.module.package.PackageDeployment.Run()
   at bolt.module.package.verbs.ShowVerb.Execute(IContext context, Command command)
   at bolt.cli.LegacyVerbExecuteFn.<>c__DisplayClass3_0.<.ctor>b__0(IContext context, Command command, CancellationToken cancellationToken)
   at bolt.cli.LegacyVerbExecutor.ExecuteAsync(IContext context, Command command, CancellationToken cancellationToken)
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<RunVerbExecutorAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteWithOutputAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue`1 nextCommands)
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory)
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)
   at bolt.Session.Run(ProgramArguments args)
2023-08-03 09:19:37.4512 | ERR | bolt.Session ::    at bolt.module.package.PackageDeployment.Run()
   at bolt.module.package.verbs.ShowVerb.Execute(IContext context, Command command)
   at bolt.cli.LegacyVerbExecuteFn.<>c__DisplayClass3_0.<.ctor>b__0(IContext context, Command command, CancellationToken cancellationToken)
   at bolt.cli.LegacyVerbExecutor.ExecuteAsync(IContext context, Command command, CancellationToken cancellationToken)
   at bolt.cli.Verb.<>c__DisplayClass11_0.<<RunVerbExecutorAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<RunVerbExecutorAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.<ExecuteWithOutputAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue`1 nextCommands)
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory)
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)
   at bolt.Session.Run(ProgramArguments args)
2023-08-03 09:19:37.4671 | INF | Microsoft.PowerPlatform.Tooling.BatchedTelemetry :: BatchedTelemetryChannel.FlushBufferToDisk Saving 9 items to transmission file.
2023-08-03 09:19:37.6208 | INF | Microsoft.PowerPlatform.Tooling.BatchedTelemetry :: BatchedTelemetryChannel.StartUploadProcess Started uploader with process id: 10956
2023-08-03 09:19:37.6208 | INF | bolt.Session :: End session. (ResponseCode: 500)
```

**Comment by JimDaly** [comment]
@TDX-RB 

Thanks for your feedback, but issues for this repo need to be about feedback on the documentation.
We can't provide technical support. Please contact support to report issues you experience.

While @snizar007 may be interested to hear of this error, there is nothing we can do in the documentation to fix this.
