### ISSUE TITLE
pac test run error 'Something went wrong when Test Engine tried to get App status.'

### ISSUE THREAD

**Issue by temmyraharjo** [MicrosoftDocs/power-platform#2490]
Hi Team,

I've got the below error when I run the test:
```
System.TimeoutException: Something went wrong when Test Engine tried to get App status.
   at Microsoft.PowerApps.TestEngine.Helpers.PollingHelper.CheckIfTimedOut(DateTime startTime, Int32 timeout, ILogger logger, String errorMessage)
   at Microsoft.PowerApps.TestEngine.Helpers.PollingHelper.<PollAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerApps.TestEngine.PowerFx.PowerFxEngine.<UpdatePowerFxModelAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerApps.TestEngine.SingleTestRunner.<RunTestAsync>d__26.MoveNext()
```

I just generated an App from Dataverse Data > the test itself is clicking the "New" button. But, I believed the test itself just successfully logged in and when the App loaded, it got this error (not yet run through the test step).
I attached the recording and the debugLog.
[e1b7af5fa6f872cada4ae16090ef87ad.webm](https://github.com/MicrosoftDocs/power-platform/assets/8713243/858a9b02-adda-4a7c-9a8a-f4ed3711698a)
[debugLogs.txt](https://github.com/MicrosoftDocs/power-platform/files/14317304/debugLogs.txt)

**Comment by JimDaly** [comment]
@temmyraharjo 

Thanks for your feedback. Issues in this repository are for changes that can be made to the documentation.  You are reporting an error, but there is no reference to any documentation to change, so nothing actionable on the documentation side.

These issues work best when you create them using the **Feedback On this page** link at the bottom of most articles. That will create an issue related to an article so we can route it to the appropriate owner. 

Test Engine is documented here [Power Apps Test Engine overview (preview)](https://learn.microsoft.com/power-apps/developer/test-engine/overview)

If you see something we can change in the documentation to address this problem, please add a link to the page.  

Otherwise, I recommend you contact technical support. I'm afraid we don't have resources to troubleshoot this with you.
