### ISSUE TITLE
Failure to import solution with Power Platform Build Tools from DevOps Pipeline using SPN connection

### ISSUE THREAD

**Issue by spasal** [MicrosoftDocs/power-platform#296]
Hi all,

I'm using a SPN connection to import a solution, but it failed with the message "GraphUserDetailNotFound Message: The user 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' was not found in Graph".

I have tried other Tasks in the build pipeline which perform OK with the same SPN connection configured.

Looking at the stack trace it looks like it happens when importing a Canvas Power App:
at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)
at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportCanvasAppSolutionDefinition>d__25.MoveNext()

Multiple reports have been made on this issue, and it has been identified as a bug.
Created a GitHub issue for visibility and follow-up purposes.

**Comment by spasal** [comment]
Fixed in 1.0.4
